language: node_js
node_js: node
cache:
  directories:
    - node_modules
#script:
#  - npm run lint
env:
  - CI=true

before_deploy:
  - npm install -g claudia
  - npm install
  - chmod +x ./deployScript/awsCred.sh
  - ./deployScript/awsCred.sh

deploy:
  provider: script
  script: npm run create-prod
  skip_cleanup: true
  on:
    branch: master